### ISSUE TITLE
Sys - Merge latest quill

### ISSUE THREAD

**Issue by garv-shah** [visual-space/visual-editor#107]
It seems like Flutter Quill has had a lot more activity recently, and quite a few features that this repo has yet to implement. Would it be worth trying to pull from the original package?

**Comment by garv-shah** [comment]
thanks for the chat on discord!

**Comment by adrian-moisa** [comment]
Glad to be of service! I'll drop here the summary:

No, it's not possible to just pull straight away. But for someone with some experience in one or the other it would be possible to retrofit. I've been watching to see the updates. Some of them were planned here as well. Neither upstream or downstream is easy. I've changed the underlying project structure by a large factor. The only way this would work is if they ditch everything changed since this repo started. 

The reason I decided to fork was simply because I had no reliable connection with the maintainer and since I needed major changes in the code base I couldn't rely on his good will to respond in timely fashion. Also I'm not really happy at all with their quality practices. This repo will grow in time. Don't stress too much about large numbers of stars on github. As long as the code has a dedicated lead that keeps pushing it further it's safe to use. For me this repo is critical for my startup, there's no going back. 

All I can tell you is that I've invested massive effort to get VE onto a new direction. And there will be YT videos upcoming. These are ready for voice over. At the moment they are pending because I'm overloaded, but I'll find some time to do the voice over and start releasing them. There will be effort to add automatic testing, online docs and demos. All in all in time this repo will gain a following

![unknown](https://user-images.githubusercontent.com/11160141/182473110-a036c316-5c3a-417d-ad62-ad6f656481ae.png)

**This is Quill:**

![unknown-1](https://user-images.githubusercontent.com/11160141/182473261-d9d81794-8382-4e1e-a97a-56156e875044.png)

**This is VE:**

![unknown-2](https://user-images.githubusercontent.com/11160141/182473298-ea39befc-12df-466f-b94e-aa9d94bf05e3.png)

Lines of code AVG from 263 down to 98. From 71 files up to 223. It's a plugin for Android Studio called Statistic. That alone tells you a lot of effort was placed into making the code base far more readable. I'll be happy to support you at implementing [formulas using latex](https://github.com/visual-space/visual-editor/issues/101).

Join on [discord](https://discord.gg/XpGygmXde4) to get advice and help or follow us on [YouTube Visual Coding](https://www.youtube.com/channel/UC2-5lfNbbErIds0Iuai8yfA) to learn more about the architecture of Visual Editor and other Flutter apps.
