### ISSUE TITLE
Sys - Snake case for file naming

### ISSUE THREAD

**Issue by aloisdeniel** [visual-space/visual-editor#110]
Not a big deal but it might trigger any experienced dart developer: the files are named with `kebab-case` instead of `snake_case`.

**Comment by adrian-moisa** [comment]
HI @aloisdeniel. I appreciate the feedback. Up to date I haven't found any clear drawback. I'd like to learn more if there's any real drawback. I've got 10 years in javascript land and I got so used to `kebab-case` that I simply can't digest the `snake_case` (I find it way easier to read, but then again, habits...). It's unclear for me why Flutter made this choice. Probably I'll have to comply in the end since the test files themselves simply demand the snake case, otherwise they are not recognised. Waiting for more feedback. Cheers!

**Comment by aloisdeniel** [comment]
I can't tell you why they chose this convention but it is part of Dart conventions and it won't change in a near future.

And now it is just like you with kebab case, when you're used to it ... it is really disturbing.  Now I find it more readable with underscores since it better separate words, maybe that's why they chose this convention.

**Comment by adrian-moisa** [comment]
Since no community member could provide any radical reason to stick with the underscore convention, this will remain as it is (until proven wrong). It works just fine as far as I can tell. Many codebases have many questionable conventions. For example Angular requires all components to end with `Component` suffix yet you can write shorter imports and tags by skipping it. And file navigation remains just fine, no confusions.
