### ISSUE TITLE
Blocks - Headings don't override the size of text

### ISSUE THREAD

**Issue by adrian-moisa** [visual-space/visual-editor#14]
This feature was developed in Quill right before the fork. it was purely tested so a lot of quality issues snuck in. Including this one. We can't override the size of sized text with headings. this is standard behaviour in other editors. The last to change the text (font size or heading) has priority in controlling the line height. As you can see the line height changes but not the font size.

For example I checked Google Docs and they have the behaviour as described above. Although in some circumstances even their implementation is rather unreliable. For example if a heading has mixed sizes of text they all scale together until they cant. So if you have a line of text with small fonts and then super large fonts, their implementation wont override the font size. I'm not sure at all if this behaviour even makes sense. I'm eager to hear your thoughts. 

https://user-images.githubusercontent.com/11160141/169512392-47e7b2d0-81bd-4bcb-92c4-263c40ac97f8.mov

Join on [discord](https://discord.gg/XpGygmXde4) to get advice and help or follow us on [YouTube Visual Coding](https://www.youtube.com/channel/UC2-5lfNbbErIds0Iuai8yfA) to learn more about the architecture of Visual Editor and other Flutter apps.

**Comment by kairan77** [comment]
Interoperability with html/word/markdown, current way of specifying styles, you have to take these aspects into account.

for the sake of argument, say for people writing their thesis with their mobile phone for example, as long as they only use 3 levels of heading nesting, when a quill document is exported as a word doc for my use case, users only need to set in their word document their prefered default h1,h2,h3 styles, and then voila, the whole document is updated accordingly, if what you said is designed and built into quill, then say if they have 70 heading occurrences in their document, after they exported the document to word, they have to set the style of 70 headings individually.

what you suggest would also make the current way of specifying styles irrelevant

if you check out good design principle for document by any big tech names such as google/apple/facebook, they all say limit the range of font family and font size to a minimum, otherwise it would make your document much harder to follow. 

The headings with 'fixed' sizes are fine, i would even argue that allowing multiple font size for paragraphs is also not necessary.

Have you tried looking at documents with rich use of different font sizes in real life? My app deals with millions of pages of documents, and I have seen/edit quite a lot of real documents first hand, i would argue one font size is enough for paragraph, when you want to use a different size in a paragraph for emphasis or anything else, you probably would be better with indentation/quote/bullet points instead, in which case you already have a different way of specifying font sizes.

Sometimes less is more, you don't have to copy other dev's design esp when their designs are wrong in the first place. For many devs, they write code without much thought, simply because it's much easier to blindly write code than to think. Much of the online editors including google docs' are pretty much crap, they don't even follow their own design principle, trust their designers' opinion rather than their junior dev's work and mistaking those lousy KPI filling effort as good design.

**Comment by adrian-moisa** [comment]
I've been looking at how Google Docs work. For me that is the gold standard of what I expect as behaviour from VE/Quill. Gdocs seems to have a system of priority between headings and test sizes (last applied, last on to take control over text size). I'll have to read more on this issue. Again, if you have any useful links, I'd be happy to read them.

**Comment by kairan77** [comment]
Google Doc's design aim is for the output to be consumed mostly by the PRINTER, things like Quill's output is mostly consumed by the computer screen/mobile screen. There is a HUGE difference there.

When writings are printed on the paper, that real estate is expensive, they take their font choices responsibly so that they could have a good time reading it off the paper.

When people write blogs and comments, that real estate belong to the platform in your case VisualSpace, so to bloggers it's free, and responsibility on good font choices goes to dust.

On screens, you usually wants to maintain a coherent look and feel, designers usually recommend using at most 5 different font families and font sizes combined (not 5 font sizes, but on both the differences in each font size and family combination).  Each of those font would serve a particular purpose, that means, for running text serving the main content, only 1 font size is optimal (politically correct on screen for that purpose, it could be of any size, but there can only be 1 font size),

You can google pdf docs for Google/Apple's/investment banks'/private equity firm's UI design guidelines handbook, what I am saying is pretty much in every one of them.

You already have visual space app page set up with a number of blog articles, just try out 2 to 3 different font sizes interleaving those main paragraphs, also try out different heading font sizes mixed together, and compare the result. 

I honestly don't see why people want to edit their offline/online docx in quill, 90% of most of the formatting options in any office suite is not even possible with markdown due to markdown/delta's inferior expressiveness of its syntax. Just like you mentioned, they already have far better options with google doc/office 360 for those scenarios.

A more important reason is that supporting different font sizes, I believe, is really difficult, what unit are you going to use? pt, px, rem etc? and then how many options? why those options? If you lock down px on drop down menus, what happens to style settings font size? who override who?, given the current state of the source code, I would be really impressed, if you could pull off all these extra issues.

**Comment by adrian-moisa** [comment]
Well yes, I agree, blogging/social media platforms don't need many font sizes and benefit from a less expressive text format. However not everybody is building a social media app or a blog. Some might use the editor to actually write full fledged corporate documents. In the case of VS I will be indeed limiting the amount of styles by not enabling text size options in the toolbar. Only heading sizes for the public content in the free plan. However for users that will pay a subscription to unlock private documents (for corporate needs) I can't simply tell them, hey no font size and no colors. It's an implicit feature that most corporate users will desire for whatever reasons. So whoever wants to limit the options can disable the text sizes picker. I don't see them as one or the other (headings or text sizes). You can have both if desired or one of them or none. That depends on each individual developer to decide.
