### ISSUE TITLE
Blocks - Code block color coding for multiple languages

### ISSUE THREAD

**Issue by adrian-moisa** [visual-space/visual-editor#18]
The current implementation of code blocks in [Flutter Quill](https://github.com/singerdmx/flutter-quill) is rather rudimentar. Not much effort was put into this feature so far. We want to develop this feature to render interactive coding tutorials in [Visual Space](https://visualspace.app/).

Color coding could be done by borrowing the tokens from another open source code editor and applying styling to the lines of text in the renderer without changing the deltas. There are some code editors from where we can borrow the list of tokens. So far I haven't researched a lot the topic. But I imagine a simple and naive implementation would search for language tokens and would apply color coding over them.

Currently the delta format can apply styling over code snippets. The idea itself is rather goofy. Except the benefit of being able to render markers, highlights and attachments using the same logic I'm seeing few reasons why we would allow full formatting in the code. For example now it is possible to add inline code snippet in a code block. Which makes no sense.

<img width="544" alt="image" src="https://user-images.githubusercontent.com/11160141/200131931-609ad8b6-2436-4f0b-a90d-97db0b304d23.png">

At the moment we would be happy with a basic code editor that provides color highlighting. But in the future we plan to add some more basic code editing features such as: syntax error highlighter or jump to token. This is by far not an easy job and I'm not even sure how far we want to go with the inline code or if this could be better done in a custom embed. I'm still thinking if the user interactions make sense.

For example I don't know for sure if selecting part of text and part of a code block should be possible. It's almost like being able to select part of text and part of an image and copy pasting them somewhere else.

**Edit**

@kthecoder has suggested the possibility of using [Microsoft's LSP Protocol](https://microsoft.github.io/language-server-protocol/) to implement autocomplete features. I believe this is somewhat beyond what a text text editor should be doing. Using a library for code editing could be a smarter move, since it's someone else's problem. Someone who specialises in code editing. However at the moment these code editors are mostly abandoned and far from complete. Ex: [code_editor](https://github.com/CodoPixel/code_editor) 

**Edit 2**

Looks like the authors of this super popular extension for Google Docs are happy with this setup. It appears they don't have access from Google to run automatic color coding at runtime. So therefore they apply styles over the existing text via a wizard that has to be manually triggered. This is insane. No way we are doing this.

<img width="904" alt="image" src="https://user-images.githubusercontent.com/11160141/200133319-3b972cde-5641-4e63-bdd0-5ace075d2478.png">

**Edit 3 - Some questions to consider**

- How will the code snippets be able to link to git repos? - Via git URL
Could be done, but then there's a major conflict. if the source code changes then the markers go stale. Also mirroring back in the repo incline comments from the code snippets hosted in articles makes also no sense. The best resolution is to keep hidden metadata that links to the git commit. Also we can count on the fact that git commits are mostly immutable (if no force push is used). The idea of automatic mirroring of code changes from repo to article code snippets has more problems than benefits. So we are better keeping a clone of the "mostly immutable" code. Just to prevent accidents. Though there's also major benefit form being able to mirror token renames from source to article. However that mass rename wont be able to safely rename the tokens in plain text. So once again automatic mirroring is a dead end solution. We keep the code snippets inline. Another problem for mirroring would be performance. In the absence of caching we would require a lot of API calls.

- How do we integrate comments inline
Using the existing API from VE. Recreating the same features in a different code editor will end up super expensive.

- How many codebases do we want to maintain?
Only one if possible.

- What happens when copying text that has reactions markers into code snippets?
Ideally we keep the reactions markers there

- Do we want autocomplete
Not right away, but on the long term yes. However this is a very complicated problem to deal with. We don't see VS doing code editing as the main editor any time soon. 

- Do we want collapsible code blocks that render simplified meta-code?
Yes, it's essential for VS tutorials. 

- Do we want to spend months/years on learning another code editor?
Not really

- Do we want a native flutter code editor or a webview?
For performance reasons we want native 100%

- Do we trust unmaintained repos, or owners that are absent?
Not at all

- Do we want to render multimedia in code?
Yes, for VS tutorials (diagrams, video, etc)

- Do we want to reuse the code snippets in other parts of VS?
Yes.

- Do we want collaborative code editing?
Yes.

Based on the questions listed above we can conclude we want to have Visual Editor in charge of rendering code blocks. We will disable rich text formatting on the code snippets and leave only code related features (highlights, markers, etc)

Join on [discord](https://discord.gg/XpGygmXde4) to get advice and help or follow us on [YouTube Visual Coding](https://www.youtube.com/channel/UC2-5lfNbbErIds0Iuai8yfA) to learn more about the architecture of Visual Editor and other Flutter apps.

**Comment by kthecoder** [comment]
Hi, love the work that is being done here. I have been thinking about how to implement rich text code editing features myself. 

I have come to the possibility of following [Microsoft's LSP Protocol](https://microsoft.github.io/language-server-protocol/)

I have been trying to look into how the LSP specification can be leveraged to support already existing VS Code extensions so as to not reinvent the wheel, and to support code language features on day one.

The Dart Team [includes an LSP within the Dart SDK](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md). I haven't yet looked into it but I was wondering if possible to use this within the text editor. 

Within the linked page above, the dart team lists which LSP features have been implemented.

"textDocument/documentHighlight" is already implemented. 

The specification is described here: [LSP Spec: Document Highlights Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentHighlight)

I believe it may be simple to have the editor run the LSP (with code based files) and interface with its JSON api to provide a simple way of implementing rich text code tooling.

However I am unaware on how this would change the editor code as it is now. Although looking into the Visual Studio Code repo they seem to also use delta for their text editor.

If this idea seems intriguing, let me know if there's anything I can help with.

**Comment by adrian-moisa** [comment]
Hi @kthecoder! Welcome aboard! I'm happy that you find this repo promising. The LSP stuff sounds very ambitious compared to the current support for code blocks (which is just bare bone text in a container). In the future if the startup I'm developing turns a profit I'd be better equipped to tackle such a challenge. At the moment I have to focus on more basic accomplishments in the rich text editor. We are a small team with little resources so we are focusing on lower hanging fruits.

I'm still pondering how it's best to deal with code blocks, wether it's best to inline them in the doc as native text or to handle them as custom embeds. I'm wondering what is the benefit/drawback of copy pasting mixed text and code, or if it's better to always treat code blocks as custom embeds.

**Comment by kthecoder** [comment]
# Prologue

If this is open source and contribute-able I would be more than happy to do the work needed after I finish my core features in my open source project. As we have the same goal for our text editor needs. 

## What's an LSP

I think you can answer your question based on your long term goals. If in the future you do want to (or if I end up contributing) use LSP, the LSP is just a JSON API that runs as a server outside the app (in an isolate in darts case) where it consumes input from the client (the text editor) and produces output. Language files are parsed using a grammar defined in a JSON file.

## Unknowns

If I am correct in my understanding and the LSP is already implemented in the Dart SDK, simply all that is left is to make calls to its JSON API and implement the client side to  support the server output. 

If I'm wrong and the Dart SDK only implements for dart or something. Then the LSP would need to be implemented.

## The Editors Goal

For the client side (text editor) it simply just has to call the JSON API and consume the output. Which means if you ask the LSP to highlight this file, give me the highlighting for it. And then interpret the output in the text editor.

When you open a file it spawns an LSP (only one for each language). So if you open up a markdown file it spawns a markdown LSP. And if you open up a dart file it spawns a dart LSP. Once it's initialized, the editor then sends the raw text to the LSP and does the processing, such as highlighting, definition search, text completion, so on. 

## Viewing the Editor Needs 

So when asking if text should be inline or embed; I would consider that mixing in markdown and dart into a file would require managing multiple language types of a single file. So that you can choose the language-type text correctly when sending it to the LSP or to be able to distinguish types for any processing needs. You need some way to differentiate languages within a single file. So you know what to process as code and what to process as text and what to process as a link. 

## Multi-Language File using LSP

Example: I have markdown on lines 1 - 25 and I send text from 1 - 25 to the markdown LSP. I have dart on lines 26 - 35. I send 26 - 35 to the LSP. 

There needs to be a way for the program to know what is dart, what is markdown, what is JavaScript, so on. You could look at a multi-languaged file as multiple separate files. 

In the LSP spec:

> The user opens a file (referred to as a document) in the tool: The tool notifies the language server that a document is open (‘textDocument/didOpen’). **From now on, the truth about the contents of the document is no longer on the file system but kept by the tool in memory.** The contents now has to be synchronized between the tool and the language server."

This means the LSP manages the function and view of opened files. The file runs in memory. The delta then is only a way to store and retrieve files. So in our case, if a user changes a file with multiple-types the editor must be able to juggle the multiple LSP APIs for each type as it displays the content within the viewport. Or what happens when a user decides to add a new language or remove one entirely.

## A Solution with LSP

So maybe the best solution is each type is a separate "document" at runtime but conjoined in the end with delta and then de-joined on open for the LSP. 

So then when saving a file the delta must know the language type of a chuck of a text file, instead of relying on file type. (Which determines how you implement the editors delta needs) And then the editor must send the file type to the LSP for a chunk of text within a file. 

## Project Needs

Since I don't fully know what else you hope to achieve with the code portion of the editor here's my thoughts on what I wish to achieve:

I for example, really want code to be able to support markdown in the comments. The best way I could think to support this is by having a markdown grammar inside the comments grammar section of a language. In this way the code is still separate from regular markdown but also supports it within blocks of code. This simply requires that the grammar supports this feature, not the editor nor the LSP. This would also make it customizable by users. But relies on an LSP implementation.

For my project, I also want to be able to take snippets of code files and inject them into a documentation markdown file (multi-languaged file). Making the documentation come alive and automatically update as changes are made by connecting code files to documentation files. The problem is that a section of code could move or be removed. (Although project repositories stay definitive for most cases) The challenge would be finding a way to sync the code in a way that makes the documentation dynamic. So instead of a line/file location, go based on function name and leverage the LSP (execute Go to Definition) to find the function when opening a documentation file. And also updating the documentation as the code changes, say its name is updated or removed. And so the only thing to store in the editor/delta would be the function name. In cases where there are duplicate names, just display the duplicates as a ListView and let the reader decide which one. 

Oh a thinking about your project, if you want things like code completion as you type code; the LSP is best for stuff like that.

## Concluding Thoughts

In the end we both aim to develop tools. And I think that The Language Server Protocol was created for tools like ours. Obviously the biggest roadblock is understanding how to use it. 

From the LSP Spec: "The idea behind the Language Server Protocol (LSP) is to standardize the protocol for how such servers and development tools communicate. This way, a single Language Server can be re-used in multiple development tools, which in turn can support multiple languages with minimal effort."
