### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by vd3d** [visual-space/visual-editor#198]
Hi,

I wish to contribute to your project, but when I try to push my first branch I got the following error message.

remote: Permission to visual-space/visual-editor.git denied to vd3d.
fatal: unable to access 'https://github.com/visual-space/visual-editor.git/': The requested URL returned error: 403
Pushing to https://github.com/visual-space/visual-editor.git

What's wrong ?

Thanks

**Comment by adrian-moisa** [comment]
You must be registered as a contributor to be able to directly push on develop. Otherwise you have to open a PR. It will get reviewed and if it checks out we accept. Otherwise we will provide feedback. I'm working on a [contributions guidelines](https://github.com/visual-space/visual-editor/blob/develop/GUIDELINES.md) document. It hasn't been completed yet.
